### PR TITLE
fix: query pagination and tx optimization

### PR DESCRIPTION
**Pull request by fnanni-0**
1. Always invoke changeStateToPending() and processVouches() together. This keeps the subgraph in sync and saves ~15k gas per registration.
2. Paginate all Submission queries.

### CODE REVIEW

**Review by hbarcelos — CHANGES_REQUESTED** [review]
LGTM, only one thing should be changed.

I also have a question:
The "pagination" schema for fetching the data assumes the result set is sorted by ID. Is that always true?

**Review by hbarcelos — APPROVED** [review]

**Comment by fnanni-0** [comment]
Look at this batch of transactions: https://etherscan.io/tx/0xedf8358c1492e52e1715e94d48eaa8aea04aa16738b02f35b9bb7d92ea0b29bf. One person vouched 6 submissions. Only one of the at a time can be processed, but the bot sent all of them. The last commit should solve this issue.

**Comment by fnanni-0** [comment]
I also propose to increase the delay to 60 min. Most batches sent by the POH bot only contain 1 transaction. IMO 60 minutes should optimize this a bit without sacrificing too much the expectations of users.

**Review by mtsalenc — APPROVED** [review]
LGTM

**Pull request merged**
